### ISSUE TITLE
人工通过和人工拒绝没反应

### ISSUE THREAD

**Issue by zlhdd108** [Tooruchan/Telegram-CAPTCHA-Bot#10]
点击人工通过和人工拒绝的时候没有反映
![image](https://user-images.githubusercontent.com/16465666/69935066-c52ce280-150e-11ea-8cc1-d87a14e580f0.png)
`ERROR:pyrogram.client.ext.dispatcher:'List' object has no attribute 'chat_members'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client/ext/dispatcher.py", line 198, in update_worker
    await handler.callback(self.client, *args)
  File "/root/Telegram-CAPTCHA-bot/main.py", line 107, in challenge_callback
    for admin in admins.chat_members
AttributeError: 'List' object has no attribute 'chat_members'`

**Comment by Tooruchan** [comment]
Fixed by remove an unused parameter in pyrogram 0.16.0:
https://github.com/Tooruchan/Telegram-CAPTCHA-Bot/commit/1be3644899b6c0c4d8ddc2ecd83d6533d228789c
