### ISSUE TITLE
非自建群组无法使用“人工通过”和“人工拒绝”

### ISSUE THREAD

**Issue by zlhdd108** [Tooruchan/Telegram-CAPTCHA-Bot#11]
发现一个现象，如果是自己创建的群组，验证的时候点击“人工通过”和“人工拒绝”都是正常的；但是非自建的群组，自己是管理员，也有所有权限，点击的时候依然会报错
![image](https://user-images.githubusercontent.com/16465666/70373879-9310eb80-1927-11ea-92fd-731f57be38f1.png)
```python
/usr/local/lib/python3.7/dist-packages/pyrogram/client/ext/dispatcher.py:198: RuntimeWarning: coroutine '_update.<locals>.challenge_timeout' was never awaited
  await handler.callback(self.client, *args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
ERROR:pyrogram.client.ext.dispatcher:'ChatMember' object has no attribute 'permissions'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client/ext/dispatcher.py", line 198, in update_worker
    await handler.callback(self.client, *args)
  File "/root/Telegram-CAPTCHA-bot/main.py", line 106, in challenge_callback
    for admin in admins
  File "/root/Telegram-CAPTCHA-bot/main.py", line 106, in <listcomp>
    for admin in admins
AttributeError: 'ChatMember' object has no attribute 'permissions'
```

**Comment by zlhdd108** [comment]
> 发现一个现象，如果是自己创建的群组，验证的时候点击“人工通过”和“人工拒绝”都是正常的；但是非自建的群组，自己是管理员，也有所有权限，点击的时候依然会报错
> ![image](https://user-images.githubusercontent.com/16465666/70373879-9310eb80-1927-11ea-92fd-731f57be38f1.png)
> 
> ```python
> /usr/local/lib/python3.7/dist-packages/pyrogram/client/ext/dispatcher.py:198: RuntimeWarning: coroutine '_update.<locals>.challenge_timeout' was never awaited
>   await handler.callback(self.client, *args)
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> ERROR:pyrogram.client.ext.dispatcher:'ChatMember' object has no attribute 'permissions'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/pyrogram/client/ext/dispatcher.py", line 198, in update_worker
>     await handler.callback(self.client, *args)
>   File "/root/Telegram-CAPTCHA-bot/main.py", line 106, in challenge_callback
>     for admin in admins
>   File "/root/Telegram-CAPTCHA-bot/main.py", line 106, in <listcomp>
>     for admin in admins
> AttributeError: 'ChatMember' object has no attribute 'permissions'
> ```

搞定了，删掉105行的"permissions"即可
原内容：
```python
or admin.permissions.can_restrict_members)
```

改为：
```python
or admin.can_restrict_members)
```

**Comment by Tooruchan** [comment]
> > 发现一个现象，如果是自己创建的群组，验证的时候点击“人工通过”和“人工拒绝”都是正常的；但是非自建的群组，自己是管理员，也有所有权限，点击的时候依然会报错
> > ![image](https://user-images.githubusercontent.com/16465666/70373879-9310eb80-1927-11ea-92fd-731f57be38f1.png)
> > ```python
> > /usr/local/lib/python3.7/dist-packages/pyrogram/client/ext/dispatcher.py:198: RuntimeWarning: coroutine '_update.<locals>.challenge_timeout' was never awaited
> >   await handler.callback(self.client, *args)
> > RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> > ERROR:pyrogram.client.ext.dispatcher:'ChatMember' object has no attribute 'permissions'
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.7/dist-packages/pyrogram/client/ext/dispatcher.py", line 198, in update_worker
> >     await handler.callback(self.client, *args)
> >   File "/root/Telegram-CAPTCHA-bot/main.py", line 106, in challenge_callback
> >     for admin in admins
> >   File "/root/Telegram-CAPTCHA-bot/main.py", line 106, in <listcomp>
> >     for admin in admins
> > AttributeError: 'ChatMember' object has no attribute 'permissions'
> > ```
> 
> 搞定了，删掉105行的"permissions"即可
> 原内容：
> 
> ```python
> or admin.permissions.can_restrict_members)
> ```
> 
> 改为：
> 
> ```python
> or admin.can_restrict_members)
> ```

感谢修复，请提交一个 Pull Request 以方便我合并代码分支。
